# -*- coding: utf-8 -*-
"""Fath Jade Suite de Fibonnaci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQFIKBVROdBU4wlwbgD7_S-TCGdR8qI4

# **Création de fonction mathématique simple en Python**

## **Implémentation de la suite de Fibonnaci**
"""

# Définition de la fonction suite de Fibonnaci 
# Avec implantation d'une saisie de donnée par l'utilisateur directement dans la fonction
def Fibonnaci():
  nterms = int(input("Entrez un nombre: "))
 
  n1 = 0
  n2 = 1
 
  print("la suite fibonacci est :")
  print(n1, ",", n2, end=", ")
 
  for i in range(2, nterms):
    suivant = n1 + n2
    print(suivant, end=", ")
 
    n1 = n2
    n2 = suivant

Fibonnaci()