# -*- coding: utf-8 -*-
"""Fath Jade fonction polynomiale.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klhM5jclHbr9bwrqMJGx3fyK650-cM5S

# **Création de fonction mathématique simple en Python**

## **Implémentation de la fonction polynomiale**
"""

# définition de la fonction polynomiale sous le nom de f(x)
def f(x):
  x = (x**3) - 1.5*(x**2)-6*x+5
  return (x)

# test du code
f(5)
