# -*- coding: utf-8 -*-
"""Fath Jade Fonction factorielle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h215RNwdgbW5SOjsT_aQ-ksOtoLAE_go

# **Création de fonction mathématique simple en Python**

## **Implémentation de la fonction factorielle**
"""

# définition de la fonction factorielle par une approche récursive 
def factorielle(n):
  if n == 0 :
      return 1
  else :
      return n * factorielle(n-1)

# test du code 
factorielle(5)

# test du code avec 0
factorielle(0)
